spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://119.27.191.130:3306/sell?characterEncoding=utf-8&useSSl=false
  redis:
    host: 119.27.191.130
    port: 6379  
